In [2]:
import numpy as np

In [1]:
#Exercício 1 no papel.

In [4]:
#Exercício 2

A = np.array([[1, 6],
              [2, 12],
              [3, 18],
              [19, 7],
              [38, 14],
              [57, 21]])

B = np.array([91, 182, 273, 445, 890, 1335])

resultado = np.linalg.lstsq(A, B)
resultado

(array([19., 12.]),
 array([4.05714319e-25]),
 np.int32(2),
 array([76.65581716, 19.54189591]))

In [20]:
A = np.array([[-5, -1],
       [-4, -2],
       [-3,  1],
       [-1,  0],
       [-4, -2]])

B = np.array([[-4,  1, -3,  1, -4],
       [-3,  0, -5, -5, -5]])

C = np.array([[-14,  13,  19,  -6,  12],
       [ -5, -14, -13,   5, -11],
       [ -4,  18,  15, -14, -15],
       [  6,  -1,   7, -11,   0],
       [ 17,  12,  13, -13, -10]])

R = C - A @ B

def norma_frobenius(R):
    soma_quadrados = 0
    for i in R:
        for j in i:
            soma_quadrados += j**2

    raiz_quadrada = np.sqrt(soma_quadrados)
    return raiz_quadrada
    

print(norma_frobenius(R))

93.42911751697112


In [21]:
#Exercício 4

#Resolvido no papel.